name: Deploy Application

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Build the application
      - name: Build the application
        run: npm run build

      # Configure SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@91.235.129.103 << 'EOF'
          pm2 stop agm-4700
          cd /home/agm-website-frontend
          git pull
          npm install
          npm run build
          pm2 start server.js
          EOF
        env:
          NODE_ENV: production
